title: Your Name
url: localhost:4000

social:
  email: maykongsn@gmail.com
  facebook:
  github: maykongsn
  instagram:
  linkedin: maykonnunes 
  gitlab:
  twitter:

projects:
  ReactSniffer: Tool for code smells detection
  JMetrics: Extracts Java code metrics
  gemdev: Jekyll minimal theme
  CIRef: Documentation of Java refactorings

plugins:
  - jekyll-seo-tag